name: Step 2, Configure your site
# This step triggers after the learner update their Pages config file.
# This workflow updates from step 2 to step 3.

on:
  workflow_dispatch:
    push:
        branches:
              - main
                  paths:
                        - _config.yml

                        permissions:
                          contents: write

                          jobs:
                            get_current_step:
                                name: Check current step number
                                    runs-on: ubuntu-latest
                                        steps:
                                              - name: Checkout
                                                      uses: actions/checkout@v4
                                                            - id: get_step
                                                                    run: |
                                                                              echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
                                                                                  outputs:
                                                                                        current_step: ${{ steps.get_step.outputs.current_step }}

                                                                                          on_config_update:
                                                                                              name: On config update
                                                                                                  needs: get_current_step
                                                                                                      if: >-
                                                                                                            ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 2 }}
                                                                                                                runs-on: ubuntu-latest
                                                                                                                    steps:
                                                                                                                          - name: Checkout
                                                                                                                                  uses: actions/checkout@v4
                                                                                                                                          with:
                                                                                                                                                    fetch-depth: 0 # Let's get all the branches.
                                                                                                                                                              ref: main
                                                                                                                                                                    - name: Update to step 3
                                                                                                                                                                            uses: skills/action-update-step@v2
                                                                                                                                                                                    with:
                                                                                                                                                                                              token: ${{ secrets.GITHUB_TOKEN }}
                                                                                                                                                                                                        from_step: 2
                                                                                                                                                                                                                  to_step: 3
                                                                                                                                                                                                                            branch_name: main
